# Generated by Django 2.2.10 on 2020-02-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='limited_time',
        ),
        migrations.AddField(
            model_name='product',
            name='limited_day',
            field=models.IntegerField(choices=[(-1, 'Every Day'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=-1, help_text='Only show this product on a specific day.', verbose_name="Time of product's availability"),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_supervisor_only',
            field=models.BooleanField(default=False, help_text='Only show this product to supervisors.', verbose_name='Is for supervisors only?'),
        ),
    ]
