# Generated by Django 2.2.9 on 2020-02-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_abstractproductclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='requires_shipping',
            field=models.BooleanField(default=False, verbose_name='Requires shipping?'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='track_stock',
            field=models.BooleanField(default=False, verbose_name='Track stock levels?'),
        ),
        migrations.DeleteModel(
            name='AbstractProductClass',
        ),
    ]
