# Generated by Django 3.1.13 on 2021-11-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='location',
            field=models.CharField(default='Tiger Den', max_length=120, verbose_name='Location'),
        ),
    ]
