# Generated by Django 3.2.16 on 2023-01-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_useraddress_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
