# Generated by Django 2.2.11 on 2020-03-09 22:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200309_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='max_alloc_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Maximum Amount of Credit Allowed to Use'),
        ),
    ]
