# Generated by Django 2.2.9 on 2020-02-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_group_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supervisor',
            field=models.CharField(blank=True, max_length=128, verbose_name='Supervisor'),
        ),
    ]
