# Generated by Django 2.2.9 on 2020-02-05 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_orders', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
    ]
