# Generated by Django 3.1.13 on 2021-11-23 05:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oscar.core.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0011_auto_20200801_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Group Order number')),
                ('location', models.CharField(max_length=50, verbose_name='Delivery Location')),
                ('currency', models.CharField(default=oscar.core.utils.get_default_currency, max_length=14, verbose_name='Currency')),
                ('total_excl_tax', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Order total (excl. tax)')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Status')),
                ('date_placed', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grouporders', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Group Order',
                'verbose_name_plural': 'Group Orders',
                'ordering': ['-date_placed'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='guest_name',
            field=models.CharField(blank=True, max_length=25, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='max_alloc_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Maximum Amount of Credit Allowed to Use'),
        ),
        migrations.AddField(
            model_name='order',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_requests', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Credit Used'),
        ),
        migrations.CreateModel(
            name='GroupOrderStatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=100, verbose_name='Old Status')),
                ('new_status', models.CharField(blank=True, max_length=100, verbose_name='New Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date Created')),
                ('group_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='order.grouporder', verbose_name='Order Status Changes')),
            ],
            options={
                'verbose_name': 'Group Order Status Change',
                'verbose_name_plural': 'Group Order Status Changes',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='group_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.grouporder', verbose_name='Group Order'),
        ),
    ]
